spring:
  profiles:
    active: common
app:
  logging:
    host: 192.168.6.182:5000

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  profiles:
    active: dev

---
# Coloque aqui suas configurações de Homologação
spring:
  profiles:
    active: homo

---
spring:
  profiles:
    active: deleteMe
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/treinamento
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: 8082